name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda todo dia à meia-noite UTC
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: davidjaneiro92
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/*.svg'
          message: 'Generated snake contribution graph'
          push: true
