name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      # ✅ Clona seu repositório
      - name: Checkout repo
        uses: actions/checkout@v3

      # ✅ Gera a cobrinha com base no seu usuário
      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: davidjaneiro92
          outputs: |
            dist/github-contribution-grid-snake.svg

      # ✅ Comita o arquivo gerado
      - name: Commit and Push
        uses: EndBug/add-and-commit@v9
        with:
          add: 'dist/*.svg'
          message: 'Generated snake contribution graph'
          push: true
